// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDCZOswW1aaUdZELjh3HFurH7idiFDTRA4',
    appId: '1:889667759656:web:c5e9aa1aac73ef338dcf1d',
    messagingSenderId: '889667759656',
    projectId: 'caffeine-connect100g',
    authDomain: 'caffeine-connect100g.firebaseapp.com',
    storageBucket: 'caffeine-connect100g.appspot.com',
    measurementId: 'G-RPZXW495DL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDpjlS7vRnf9aVrhgeiz_hosa6mhgOOefo',
    appId: '1:889667759656:android:d885bf410cfee4d98dcf1d',
    messagingSenderId: '889667759656',
    projectId: 'caffeine-connect100g',
    storageBucket: 'caffeine-connect100g.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAGNu-ZuqYlEjRWqguElUYs5-A8_P6Z_yQ',
    appId: '1:889667759656:ios:a54a1b7cd2f502018dcf1d',
    messagingSenderId: '889667759656',
    projectId: 'caffeine-connect100g',
    storageBucket: 'caffeine-connect100g.appspot.com',
    iosBundleId: 'com.example.caffeineConnectfull',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAGNu-ZuqYlEjRWqguElUYs5-A8_P6Z_yQ',
    appId: '1:889667759656:ios:61f68d575040518b8dcf1d',
    messagingSenderId: '889667759656',
    projectId: 'caffeine-connect100g',
    storageBucket: 'caffeine-connect100g.appspot.com',
    iosBundleId: 'com.example.caffeineConnectfull.RunnerTests',
  );
}
